import { Message, MessageType } from "@/components/chat-sdk/types";

export const messages: Message[] = [
  {
    id: "15",
    content: { text: "Perfect! See you there! " },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "read",
  },
  {
    id: "14",
    content: { text: "I'll bring the popcorn " },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "read",
  },
  {
    id: "13",
    content: { text: "Great idea!" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "read",
  },
  {
    id: "12",
    content: { text: "Time to go to the movies!" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "read",
  },
  {
    id: "11",
    content: { text: "😀" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "read",
  },
  {
    id: "10",
    content: { text: "😁" },
    createdAt: new Date(),
    from: "user-2",
    isReceived: true,
    type: MessageType.TEXT,
  },
  {
    id: "9",
    content: { text: "Let's go to the movies!" },
    createdAt: new Date(),
    from: "user-2",
    isReceived: true,
    type: MessageType.TEXT,
  },
  {
    id: "8",
    content: { text: "Yes, I would like to go to the movies!" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "delivered",
  },
  {
    id: "7",
    content: { text: "Would you like to go to the movies?" },
    createdAt: new Date(),
    from: "user-2",
    isReceived: true,
    type: MessageType.TEXT,
  },
  {
    id: "6",
    content: { text: "I'm good, thank you!" },
    createdAt: new Date(),
    from: "user-2",
    isReceived: true,
    type: MessageType.TEXT,
  },
  {
    id: "5",
    content: { text: "Nice to meet you, John!" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "sent",
  },
  {
    id: "4",
    content: { text: "My name is John Doe" },
    createdAt: new Date(),
    from: "user-2",
    isReceived: true,
    type: MessageType.TEXT,
  },
  {
    id: "3",
    content: { text: "What's your name?" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "sent",
  },
  {
    id: "2",
    content: { text: "I'm good, thank you!" },
    createdAt: new Date(),
    from: "user-2",
    isReceived: true,
    type: MessageType.TEXT,
  },
  {
    id: "1",
    content: { text: "Hello, how are you?" },
    createdAt: new Date(),
    from: "user-1",
    isReceived: false,
    type: MessageType.TEXT,
    status: "sent",
  },
]